### ISSUE TITLE
Could this plugin theoretically work with dimension resources?

### ISSUE THREAD

**Issue by mannodermaus** [LikeTheSalad/android-stem#1]
Thank you for publishing this plugin! I hope to be able to integrate it into a project some day.

One of the longest-running grievances I've had with the Android resource system is the missing ability to reference dimension resources for calculations. Whenever this has been necessary, awful comments had to express the intent behind the compound values. Lo and behold if one of the referenced values changes, the sum must do as well, or else havoc breaks loose:

```xml
<!-- app/.../dimens.xml -->
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <dimen name="outer_padding">8dp</dimen>
    <dimen name="inner_padding">4dp</dimen>
    <dimen name="combined_padding">12dp</dimen> <!-- outer_padding + inner_padding -->
</resources>
```

I'm envisioning a world where `dimen` resources could be referenced and calculated as well. Do you reckon that the plugin would have the capability to perform such tasks?

```xml
<!-- app/.../dimens.xml -->
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <dimen name="outer_padding">8dp</dimen>
    <dimen name="inner_padding">4dp</dimen>
    <string name="template_outer_padding" type="dimen">${outer_padding} + ${inner_padding}</string>
</resources>
```

```xml
<!-- build/.../dimens.xml -->
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <dimen name="outer_padding">12dp</dimen>
</resources>
```

I realize that the different units of measurement (dp vs. sp vs. px) might pose a problem. However, this could be mitigated by failing at build time when units are mixed within an expression. Also, since there would probably be an expression engine behind this, the feature wouldn't be limited to simple addition:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- This could also work -->
    <string name="template_other_padding" type="dimen">2 * ${outer_padding} - ${inner_padding}</string>
</resources>
```

Please let me know if you think that this might be feasible for the scope of a resource-generator plugin like yours. Again, thanks for maintaining this!

**Comment by LikeTheSalad** [comment]
Hi @mannodermaus - Thanks for your feedback!

I understand, I think it would be a great option to have as well. As for whether it is possible or not, I'm sure it is :) The resources gathering is just about reading XML tags all over the project's res dirs which are already provided by the android build plugin. Although I think such feature wouldn't fit for the scope of this particular plugin but as a standalone plugin instead. - I'm currently working on other projects which doesn't let me much time left for new things, but after I'm done with those, I can start with that in case no one else have done so by then 👍

Thanks again!

**Comment by LikeTheSalad** [comment]
Hi @mannodermaus, a lot has happened since the last time I visited this issue, but generally speaking I think this plugin has reached a level of maturity that makes me more comfortable to explore some updates for it. That being said, after doing some quick testing on using templates for dimens, the same way as this plugins does it for strings, I noticed that things won't be the same, unfortunately, as the AGP does some validations to make sure that the values set to dimen resources are actually dimens and nothing else... Some workarounds could be made of course, such as the one that you pointed out of using "string" to define custom dimens, or maybe defining an empty dimen with a new attribute that defines the "formula" if you will. Also, there's some additional work needed for gathering different variations of dimens, similarly the way this plugin does with string languages for example, but for different "values-sw...dp" folders in this case, but none of that would be reusable from this plugin, which would make that work more of a new plugin on its own that I haven't taken into consideration to build and maintain.

At some point I decided to build certain open source tools, which is why I built this plugin, and [Aaper](https://github.com/LikeTheSalad/aaper), and the latter forced me to build [Android-Buddy](https://github.com/LikeTheSalad/android-buddy) as well, which ended up being unexpectedly interesting to work on, and I've also thought about a couple of other tools that, due to my 9-6 work plus the support for the existing tools, I haven't had a chance to even starting working on those, and I wouldn't like to stray away too much from my initial goals, which is why I don't see feasible to work on the idea you proposed, which is a great idea, is just that I can't see a way to leverage it neither from my existing projects nor for future ones, and I've already set my goals from long ago, so I'd like to stick to them for now.

I'm going to close this ticket because of the above, as I can't guarantee you I'd ever become available to address your idea, and I don't think it makes sense to keep this open when it's more related to a new project rather than a feature to the existing one.  Again, your idea is pretty cool, I just can't commit to building and maintaining it based on my previously set goals and current tools support. If you want to give it a try yourself and would like to reuse code and ideas from this plugin, I'd be happy to answer any questions you might have.

**Comment by mannodermaus** [comment]
Thank you for the feedback, @LikeTheSalad! :) No worries at all. I suppose that with Jetpack Compose on the map now and the virtues of simply using Kotlin for dp arithmetics, this feature request would be a lot less important in today's landscape. I appreciate the thought you've given it. Have a good one ✨
