### ISSUE TITLE
Is there a way to Customize the ${} template?

### ISSUE THREAD

**Issue by jjinyuwu** [LikeTheSalad/android-stem#112]
Is there a way to Customize the ${} template? for example, what if we want to use {} rather than ${}. Thanks!!!

**Comment by LikeTheSalad** [comment]
Not at the moment, although I'm a bit curious to learn more about your experience with the existing marker (`${}`). Is it causing any troubles, such as clashing with other tool's syntax or the like?

**Comment by jjinyuwu** [comment]
@LikeTheSalad Hi Thanks for replying. I am trying to use a localization API to do the translation. However, they don't support skipping the ${} except certain pattern. We are using our own script to replace everything at the moment. Figure it would be a great feature to customize the default template.

**Comment by LikeTheSalad** [comment]
I understand. I haven't tried to add that functionality so far though it sounds very handy and it's probably not too complicated to make it work. I'll have a look at how it can be added.

**Comment by LikeTheSalad** [comment]
Hi @jjinyuwu 

The latest version (`2.12.0`) has this feature supported. You'd need to add the `placeholder` config param to your build.gradle file in order to set your own delimiters. You can see more details [here](https://github.com/LikeTheSalad/android-stem?tab=readme-ov-file#3--configuration).

Feel free to reopen this issue if needed.

**Comment by jjinyuwu** [comment]
@LikeTheSalad Thanks!! You are awesome Salad!!
