### ISSUE TITLE
Make the plug in works for modules

### ISSUE THREAD

**Issue by bmarty** [LikeTheSalad/android-stem#14]
The plug in works fine on applications, but not on module (with plugin 'com.android.library').

Do you think it is possible to make it work also for modules?

The context is this one: https://github.com/vector-im/element-android/issues/3955

**Comment by danaimset** [comment]
Hi @LikeTheSalad  I can confirm that the plugin doesn't work for library project. For example:
I have a module `com.android.library` with string resource defined there aka
`<string name="template_welcome">Welcome to ${appName}</string>`
So the resolved string which is `welcome` is generated under corresponding folder in main app's module build directory and cannot be referenced from the xml or sources of library module. I expected to have `welcome` string resources generated under resolved directory inside module build directory.
Could it be something wrong in my project configuration or string resource resolver is not applicable for library projects?

**Comment by LikeTheSalad** [comment]
Hi @bmarty @danaimset - The new version 2.0.0 is available, there are a lot of changes in it, including the fact that adding the "template_" prefix is no longer needed, and also, there's a new plugin ID created just for [Android Library projects](https://github.com/LikeTheSalad/android-stem#23--adding-it-to-your-own-android-libraries-optional). Please bear in mind that a lot of things have changed in this new version 2.0.0, there's a rebranding along with new dependencies parameters and plugin ID, so in order to add the new version into your project, I recommend you to check again the README's instructions: https://github.com/LikeTheSalad/android-stem#21--changes-to-your-roots-buildgradle-file
