### ISSUE TITLE
Remove templates from output binary

### ISSUE THREAD

**Issue by alipov** [LikeTheSalad/android-stem#15]
@LikeTheSalad First of all I'd like to thank you for a great plugin!

Since templates by themselves are not intended to be directly used, my assumption is that they can be safely removed once plugin finished processing them. However, that's not the case: I've noticed that template string resources are not being removed from target APK file - and therefore increase precious APK file size.  

Have you considered to implement templates removal? If yes, and chose not to remove - what's the rationale behind it?

**Comment by LikeTheSalad** [comment]
Hi @alipov - Many thanks for your feedback!

That's actually something that I'm considering at the moment, ideally I want to make the templates to not get into the final build, although I'm pondering about the different types of solutions in a way that wouldn't compromise performance and usability. The thing is that, the Android build plugin takes every resource from those dirs, so if we want to avoid it to get the templates, either we'd have to place them out of the res dirs, or remove those before the android plugin gathers them (which would be hacky, which is also something I'm trying to avoid, since I'd like to make this tool stable across different android build plugin versions).

I've been thinking mostly about defining a separate file only for templates, which could be easier to hide from the android build plugin, rather than the way it is now where users can place templates anywhere, as it's not feasible to try and remove only the templates strings from the user's xml files 😅 -  The thing I'm almost certain is that, by making this change, probably the way of using this plugin would change a little bit, because, if for example I define an template-dedicated xml file, then it wouldn't make sense to make people name their templates with the "template_" prefix for example.

So to summarise, I am thinking about adding this feature, I'm currently finishing off with the issue #10 so I should start with this next, and it might take some time as I want to keep all the current functionalities but probably with a slightly different user interface. In the meantime, I've done some research about current available tools that would allow to get rid of the templates for the final build, and I think you might find this useful as a temporary solution: https://developer.android.com/studio/build/shrink-code#keep-resources - It allows you to define in an xml file, the list of resources you'd like to discard, where you have to use the name of the resources, or only part of the names and then use a wildcard to match all the ones that start with some common name, so maybe you should be able of defining something like `tools:discard="@string/template_*"` and it should take care of all the string templates. It uses R8, and you need to enable this feature in gradle for it to work using `shrinkResources true` as they explain there as well: https://developer.android.com/studio/build/shrink-code#enable

I hope it can help you for now while I take some time to come up with a nice solution within this plugin.

**Comment by alipov** [comment]
@LikeTheSalad Thanks a lot for a prompt and detailed response!

> so maybe you should be able of defining something like `tools:discard="@string/template_*"` and it should take care of all the string templates

I've tried several ways to configure strings discarding (specific string value, the whole resource file containing string templates), but none of them worked.  

Then I've jumped into AGP's source code (gradle_3.4.0 is the latest branch I found), [they mention](https://android.googlesource.com/platform/tools/base/+/refs/tags/gradle_3.4.0/build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/ResourceUsageAnalyzer.java#137) the following:  
> For now, for reasons detailed in the code, this only applies to file-based resources like layouts, menus and drawables, not value-based resources like strings and dimensions.  

and [then](https://android.googlesource.com/platform/tools/base/+/refs/tags/gradle_3.4.0/build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/ResourceUsageAnalyzer.java#151):  
> Whether we support running aapt twice, to regenerate the resources.arsc file such that we can strip out value resources as well. **We don't do this yet**, for reasons detailed in the ShrinkResources task

and [also](https://android.googlesource.com/platform/tools/base/+/refs/tags/gradle_3.4.0/build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/ResourceUsageAnalyzer.java#404):  

> "Removes" resources from an .ap_ file by writing it out while filtering out unused resources. This won't touch the values XML data (resources.arsc) but will remove the individual file-based resources, which is where most of the data is anyway (usually in drawable bitmaps)

So it seems that the resource shrinker doesn't touch the `resources.arsc` file (which contains the strings), even though the [required support](https://issuetracker.google.com/issues/36996480) in aapt2 was already implemented.

**Comment by LikeTheSalad** [comment]
Hi @alipov, many thanks for your detailed explanation. I see, it seems like they have misleading information in the android devs website then. That's quite disappointing tbh.

I guess for now there's no alternatives using AGP existing tools, I'll leave this ticket open and I'm planning to take it next. Thanks again for your feedback.

**Comment by bmarty** [comment]
This problem was mentioned in https://github.com/LikeTheSalad/android-string-reference/issues/10#issuecomment-791354031, thanks @alipov for creating a dedicated issue about it!

**Comment by LikeTheSalad** [comment]
Hi @alipov - The new version 2.0.0 is now available, with this new version it is no longer needed to define your templates by adding the "template_" prefix to them, meaning that the same Android Plugin will take care of removing duplicates during compilation, thus avoiding unnecessary resources to get into your final build. Although, please bear in mind that a lot of things have changed in this new version 2.0.0, there's a rebranding along with new dependencies parameters and plugin ID, so in order to add the new version into your project, I recommend you to check again the README's instructions: https://github.com/LikeTheSalad/android-stem#21--changes-to-your-roots-buildgradle-file
