### ISSUE TITLE
duplicate error for 'es-rES' locale in facebook sdk

### ISSUE THREAD

**Issue by nk-contorra** [LikeTheSalad/android-stem#17]
i have this import in build.gradle
implementation 'com.facebook.android:facebook-android-sdk:4.42.0'

and got this error:
Execution failed for task ':main:stringDebugResourceLocator'.
> Found resources with the same name 'com_facebook_device_auth_instructions' within the same variant '--dependency--' for the same language 'es-rES'. Resource names must be unique within a singlevariant-language environment

does preprocessor touching external libs? way to turn this off? thanks.

**Comment by kgnkbyl** [comment]
Same issue with the latest facebook sdk. When i update it to the latest version. 
Any solution for this?

**Comment by LikeTheSalad** [comment]
Hi @nk-contorra, @kgnkbyl The new version 2.0.0 is now available. This new version only uses resources from your own libraries which you want to define as "resource providers", so it will no longer check all of your project dependencies, only the ones you want it to check (if any), meaning that the Facebook issue should be gone now. Although, please bear in mind that a lot of things have changed in this new version 2.0.0, there's a rebranding along with new dependencies parameters and plugin ID, so in order to add the new version into your project, I recommend you to check again the README's instructions: https://github.com/LikeTheSalad/android-stem#21--changes-to-your-roots-buildgradle-file
