### ISSUE TITLE
IDE errors Unresolved reference

### ISSUE THREAD

**Issue by vvasilev92** [LikeTheSalad/android-stem#18]
Is there a way to fix the Android Studio Unresolved Reference errors. I guess it's seeing the resources with the "template_" prefix but those aren't supposed to be used. Would that have to be handled via a plugin on android studio itself somehow?

**Comment by LikeTheSalad** [comment]
Hi @vvasilev92 - I'm currently working on the next major version, 2.0.0, where you'd be able to define templates without the "template_" prefix. That way it will no longer be needed to compile to be able of referencing the resolved string as it's needed in the current versions.

**Comment by LikeTheSalad** [comment]
Hi @vvasilev92 - Version 2.0.0 is now available, now the templates will no longer need to be named with the "template_" prefix, so there shouldn't be any unused resources in your project anymore when you switch to it. Although, please bear in mind that a lot of things have changed in this new version 2.0.0, there's a rebranding along with new dependencies parameters and plugin ID, so in order to add the new version into your project, I recommend you to check again the README's instructions: https://github.com/LikeTheSalad/android-stem#21--changes-to-your-roots-buildgradle-file
