### ISSUE TITLE
Apply templates for libraries during the test compilation phase

### ISSUE THREAD

**Issue by mattinger** [LikeTheSalad/android-stem#88]
So i'm new to this plugin and i'm trying to set things up.  I have a library module that's providing templated strings, and an app which is using them (we're a multimodule project with individual modules for each feature). 

I'm able to apply branding strings for the application.  But i'd like to be able to supply additional test resources to my library module and resolve templates for the test configuration so that I can snapshot test properly.

So if i have something like this in my module

```
<string name="greeting">Welcome to ${productName}</string>
```

And this in the app:

```
<string name="productName">Product 1</string>
```

It will render properly.  however, i like my snapshot tests, which reside in the library module, to be able to resolve to "Welcome to Product 1" instead of "Welcome to ${productName}"

I'm not sure if i'm missing something, but i can't add the regular plugin to the library, and putting the same resource file for the brandable strings under src/test/res/values does not do anything.

**Comment by LikeTheSalad** [comment]
Hi @mattinger 

Support for resolving templates is only available for android application projects. If said support would be added to library projects it could create a problem because the templates would get resolved when the library is compiled, effectively losing the template for when the application gets compiled, which is when it's actually needed.

Technically speaking, by the use of workarounds and config parameters and gradle tasks shenanigans, it might be possible to create a use case for the template resolving that works only when running tests and is ignored otherwise, but the effort to make this possible is bigger than what I can commit to do since I'm focusing on key functionality features to maintain this project. I'm open to reviewing PRs in case you're interested to enable that use case.

For the time being, what I'd recommend to do is to create a wrapper android application project that includes the library you'd like to test, and run your verifications on this "test app" wrapper.

Since there's no action I'm planning to take for this issue I'll close it, though feel free to reopen it in case you're interested to contribute the changes to make this work, in case the wrapper tester might not work for you.
